language: node_js
node_js:
- '0.11'
- '0.10'
before_script:
- npm install -g karma-cli
notifications:
  email: false
env:
  global:
  - secure: GSd/1rnfg2I+eYeB26kMhU6G2tusIr7FtcPWrwtGd+UDc5QAAH0exRr8+KPTgSrCItw5mGVZLoR9wD4Y+KqZtAhUsPEuA1aI6UqmV9xvuulKyKkd9tTpki1+NsIDVcwbjg4+PEn0HYWST0/6r0FcQ/v23qhKBX+G57j+7NA0Ltg=
  - secure: XqbGBwA5bKnPjVcKrg8mG1vdXpPwifOMSEKnXkwEtIdbc44fF95W+M7FDzO+fz9hA7H52JmZoa3soeSk/996IbJHK1wJXKyHHvEE+U6hXjHG16hQaauugJegmhy+XuafmRqFNKOk4TBKAaUCnBIwkR1tFG3vZD5+/D6H9XBFvSY=
